name: Update RSS Feeds

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" # Specify the Go version you're using

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          go get github.com/mmcdole/gofeed
          go get golang.org/x/net/html

      - name: Manage folders
        run: |
          rm -rf ereyesterday/*
          mv yesterday/* ereyesterday/ || true
          mv today/* yesterday/ || true

      - name: Run Go script
        run: go run main.go

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feeds" && git push)

  deploy:
    runs-on: ubuntu-latest
    needs: update-feeds

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
